---
- name: Build Web Application
  hosts: your_web_servers
  become: true
  vars:
    app_name: my_web_app
    mysql_root_password: your_mysql_root_password
    mysql_db_name: your_database_name
    mysql_db_user: your_database_user
    mysql_db_password: your_database_password

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - mysql-server
        - python3
        - python3-pip

    - name: Configure MySQL
      debconf:
        name: "mysql-server"
        question: "mysql-server/root_password"
        value: "{{ mysql_root_password }}"
        vtype: "password"
      notify: Restart MySQL

    - name: Install Python dependencies
      pip:
        name:
          - Flask
          - flask-mysql

    - name: Copy application files
      copy:
        src: "{{ item.src }}"
        dest: "/opt/{{ app_name }}/{{ item.dest }}"
      with_items:
        - { src: "app.py", dest: "app.py" }
        - { src: "templates/", dest: "templates/" }
        - { src: "static/", dest: "static/" }

    - name: Set up MySQL database and user
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      notify: Grant privileges

    - name: Load initial database schema
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: import
        target: "/opt/{{ app_name }}/schema.sql"
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Start the web application
      command: python3 /opt/{{ app_name }}/app.py

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

    - name: Grant privileges
      mysql_user:
        name: "{{ mysql_db_user }}"
        password: "{{ mysql_db_password }}"
        priv: "{{ mysql_db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
